experiment:
  name: iris_medium_nopreprocess
  seed: 42
  results_dir: Results/iris_medium_nopreprocess
  complexity: medium

data:
  tabular:
    path: datasets/iris/iris_binary.csv
    label_col: label
    id_col: Key
    sep: ";"

preprocessing:
  zscore: false
  feature_selection: false

cv:
  strategy: kfold
  n_folds: 5
  seeds: [42]

models:
  - name: xgboost
    type: tabular
  - name: kernel_svm
    type: tabular_quantum
  - name: qcnn_muw
    type: tabular_quantum

evaluation:
  metrics: [bacc, auc, sensitivity, specificity]

reporting:
  markdown: true
  latex: true
